# Django modules
from django.shortcuts import render

# Python and system-wide modules
import time
import facebook

# Local modules
from constants import *


# Temporary access access_token generated by Facebook's Graph API Explorer
access_token = 'CAACEdEose0cBAMQWBwstSMZC0zZAVFgHiG2UcpCZBczCkSflP7GnaMHKoG0HP87PPI4FwnQOoiatZC23PgNaC9iQKmecUCnHekmPAzEFhBaK1J8OJxPtcz36s2ckb0xoWvhGUttGEoueaO9QnfZCeAXvNHYSHLoOpzxPCbKmltlJQSoPOqAE0oQkrbtbZC4DYZD'


def index(request):
	graph = facebook.GraphAPI(access_token, timeout=REQUEST_TIMEOUT_IN_SECONDS)
	profile = graph.get_object('me')

	start = time.time()
	friends_data = graph.get_connections('me', 'friends')['data']
	end = time.time()
	print('Graph API request for friends took ' + str('%.2f' % (end - start)) + ' seconds.')

	start = time.time()
	friends_data = graph.fql(FRIENDS_ID_AND_NAME_QUERY)
	end = time.time()
	print('FQL query for friends took ' + str('%.2f' % (end - start)) + ' seconds.')

	start = time.time()
	friendships_between_friends = graph.fql(FRIENDSHIPS_BETWEEN_FRIENDS_QUERY)
	end = time.time()
	print('FQL query for connections between friends took ' + str('%.2f' % (end - start)) + ' seconds.')

	# Assemble a list of friend dictionaries with names and IDs
	friends = []
	for friend_data in friends_data:
		friends += [
			{
				'name': friend_data['name'],
				'ID': friend_data['uid'],
			}
		]

	# Render page with friend information
	return render(request, 'friends/index.html', {'friends': friends, 'number_of_connections_between_friends': len(friendships_between_friends)})








